### ISSUE TITLE
Works out of the box?

### ISSUE THREAD

**Issue by tonivdv** [rednose-public/RednoseKerberosBundle#1]
Hey,

This is maybe an odd question, but I would like to know if this works out of the box without any additional apache mod etc ... ?

I got a request to support an authentication from Kerberos but at the moment I have no additional info, so hope you can enlighten me on some basic things? Thanks

**Comment by SavageTiger** [comment]
This bundle is a Symfony2 UserProvider that reads the REMOTE_USER server enviroment variable to determine what token it should create (see the framework bundle for auto user creation). So to answer your question, no you will need to configure mod_auth_kerb in apache within a kerberized enviroment. mod_auth_kerb is the module that will then create the REMOTE_USER variable.

This is mostly used for intranets only, so if you have to support over the internet singlesignon i suggest you look into SAML.

(Also getting a kerberized enviroment up and running is a massive pain in the a...)

Good luck :)

**Comment by tonivdv** [comment]
Thank you @SavageTiger .
